require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Metrics/MethodLength:
  Exclude:
    - "**/*/test_*.rb"

Metrics/AbcSize:
  Exclude:
    - "**/*/test_*.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*/test_*.rb"
    - "*.gemspec"

Metrics/ClassLength:
  Exclude:
    - "**/*/test_*.rb"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
